{% set name = "rospkg" %}
{% set version = "1.5.0" %}
{% set sha256 = "6290b6ffb69aec9c00178345ddc9036aaecf29ca3bc17ba21eee63d9d4d8ff31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ros-infrastructure/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - rosversion = rospkg.rosversion:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - catkin_pkg
    - pyyaml
    - distro

test:
  commands:
    - rosversion --help
    - rosversion --distro
  imports:
    - rospkg

about:
  home: http://wiki.ros.org/rospkg
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Standalone Python library for the ROS package system
  dev_url: https://github.com/ros-infrastructure/rospkg

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - wolfv
    - lesteve
    - seanyen
