{% set name = "rospkg" %}
{% set version = "1.2.3" %}
{% set sha256 = "0fcd87b7c3a74cf37eb47ce818cb43108ddfea18621e0cb09574da9d19a0b77f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ros-infrastructure/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - rosversion = rospkg.rosversion:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - catkin_pkg
    - pyyaml
    - distro

test:
  commands:
    - rosversion --help
    - rosversion --distro
  imports:
    - rospkg

about:
  home: http://wiki.ros.org/rospkg
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Standalone Python library for the ROS package system'
  dev_url: https://github.com/ros-infrastructure/rospkg

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
