{% set name = "rospkg" %}
{% set version = "1.6.0" %}
{% set sha256 = "9341c8af5f547888ab484ee61b53d8447b6a52081222d2d5257757ab374c657f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ros-infrastructure/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - rosversion = rospkg.rosversion:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - catkin_pkg
    - pyyaml
    - distro

test:
  requires:
    - python {{ python_min }}
  commands:
    - rosversion --help
    - rosversion --distro
  imports:
    - rospkg

about:
  home: http://wiki.ros.org/rospkg
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Standalone Python library for the ROS package system
  dev_url: https://github.com/ros-infrastructure/rospkg

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - wolfv
    - seanyen
